name: '[PR] Semantic PR'

on:
  pull_request_target:
    branches:
      - main
    types: [ opened, edited, synchronize ]

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            major
            feat
            fix
            bug
            bugfix
            maint
            docs

          requireScope: false
          ignoreLabels: |
            type: dependencies
          wip: true
