name: '[Release] PR Labeler'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release-labeller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}